<?php

namespace ADR\Bundle\Symfony2ErlangBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RestController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ADR\Bundle\Symfony2ErlangBundle\Controller\RestController();
        return $instance;
    }
}
